import { database } from "../src/lib/db";
import { createDrop, enterDrop, drawDrop } from "../src/lib/service";
import { demoCode } from "../src/lib/domain";
if (
  process.env.NODE_ENV === "production" ||
  process.env.VERCEL ||
  process.env.DATABASE_URL
)
  throw new Error("Setup is restricted to a local demo database.");
const windowSeconds = Number(process.env.TENJO_DEMO_WINDOW_SECONDS || 86400);
if (
  !Number.isInteger(windowSeconds) ||
  windowSeconds < 30 ||
  windowSeconds > 86400
)
  throw new Error("Demo entry window must be 30–86400 seconds.");
const db = await database();
const existing = await db.query("SELECT id FROM drops WHERE id=$1", [
  "weekend-drop",
]);
if (existing.rows.length) {
  console.log(
    "Demo already exists; no records changed. Use a new TENJO_LOCAL_DB path for a fresh rehearsal.",
  );
  await db.close();
  process.exit(0);
}
const base = Date.now() - 86400000;
for (let i = 0; i < 3; i++) {
  const opens = new Date(base + i * 60000);
  const closes = new Date(opens.getTime() + 30000);
  const drop = await createDrop(
    db,
    {
      title: `Setup draw ${i + 1}`,
      description: "Local demo history, generated by the setup script.",
      series_id: "weekend-tech",
      series_name: "Weekend tech club",
      items: 1,
      opens_at: opens.toISOString(),
      closes_at: closes.toISOString(),
    },
    { demo: true, setup: true, id: `setup-${i + 1}` },
  );
  for (const fan of ["fan-a", `setup-winner-${i}`])
    await enterDrop(
      db,
      drop.id,
      { code: demoCode(fan), demo: true },
      new Date(opens.getTime() + 1000),
    );
  // Choose the other setup entrant, but use the exact same draw + settlement path.
  const codes = [demoCode("fan-a"), demoCode(`setup-winner-${i}`)].sort();
  const roll = codes[0] === demoCode("fan-a") ? i + 1 : 0;
  await drawDrop(db, drop.id, new Date(closes.getTime() + 1000), () => roll);
}
const drop = await createDrop(
  db,
  {
    title: "The weekend console drop",
    description:
      "A little less luck. A little more recognition. Three consoles, reserved for the people who keep showing up.",
    series_id: "weekend-tech",
    series_name: "Weekend tech club",
    items: 3,
    opens_at: new Date(Date.now() - 60000).toISOString(),
    closes_at: new Date(Date.now() + windowSeconds * 1000).toISOString(),
  },
  { demo: true, id: "weekend-drop" },
);
for (const fan of ["fan-b", "fan-c", "fan-d", "fan-e"])
  await enterDrop(db, drop.id, { code: demoCode(fan), demo: true });
console.log(
  "Local demo ready at /drops/weekend-drop. Fan A has 3 losses from labelled setup draws and has not entered.",
);
console.log("No World ID verification or Sui transaction was simulated.");
await db.close();
